apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-management-api
  labels:
    app: ssl-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssl-management-api
  template:
    metadata:
      labels:
        app: ssl-management-api
    spec:
      containers:
        - name: ssl-management-api
          image: <image-repo>:<tag>
          ports:
            - containerPort: 8001
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "ssl_management.settings"
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-management-api
  labels:
    app: ssl-management-api
spec:
  selector:
    app: ssl-management-api  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 8001             # Port exposed by the Service
      targetPort: 8001       # Container port in the Deployment
  type: ClusterIP            # Default service type, accessible within the cluster
---